version: "3.0"

services:
    beacon_node:
        build:
            context: lighthouse
        volumes:
            - lighthouse-data:/root/.lighthouse
            - ./scripts:/root/scripts
            - ./network:/root/network
        ports:
            - 5052:5052/tcp
            - 5053:5053/tcp
            - 9000:9000/tcp
            - 9000:9000/udp
        env_file: .env
        command: /root/scripts/start-beacon-node.sh
        restart: unless-stopped
    validator_client:
        build:
            context: lighthouse
        volumes:
            - lighthouse-data:/root/.lighthouse
            - ./scripts:/root/scripts
        depends_on:
            - beacon_node
        env_file: .env
        command: /root/scripts/start-validator-client.sh
        restart: unless-stopped
    geth:
        build:
            context: geth
        volumes:
            - geth:/root/.ethereum
            - ./scripts:/root/scripts
        ports:
            - 30303:30303/tcp
            - 30303:30303/udp
        env_file: .env
        command: sh /root/scripts/start-geth.sh
        restart: unless-stopped
volumes:
  geth:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/sda1/ethereum'
  lighthouse-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/sda1/lighthouse-data'
