version: "3.0"

services:
    beacon_node:
        image: syuan100/lighthouse:latest_arm64
        volumes:
            - lighthouse-data:/root/.lighthouse
            - ./scripts:/root/scripts
            - ./network:/root/network
        ports:
            - 5052:5052/tcp
            - 5053:5053/tcp
            - 9000:9000/tcp
            - 9000:9000/udp
        env_file: .env
        command: sh /root/scripts/start-beacon-node.sh
    validator_client:
        image: syuan100/lighthouse:latest_arm64
        volumes:
            - lighthouse-data:/root/.lighthouse
            - ./scripts:/root/scripts
        depends_on:
            - beacon_node
        env_file: .env
        command: sh /root/scripts/start-validator-client.sh
    geth:
        image: syuan100/go-ethereum:1.9.16-arm64
        volumes:
            - geth:/root/.ethereum
            - ./scripts:/root/scripts
        ports:
            - 30303:30303/tcp
            - 30303:30303/udp
        env_file: .env
        command: ["--goerli", "--http", "--http.addr", "0.0.0.0", "--http.vhosts=*", "--cache", "512"]
volumes:
  geth:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/sda1/ethereum'
  lighthouse-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/sda1/lighthouse-data'
